application: meatog
version: test
runtime: python
api_version: 1

#builtins:
#- datastore_admin: on

handlers:

- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /static/(.*)
  static_files: static/\1
  upload: static/.*

- url: /.*
  script: main.py
